// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbQiNL-FXxjhlnsknBCoBds3s-hfy8SnY',
    appId: '1:24158406196:web:f88fc0e498f1baa49bec61',
    messagingSenderId: '24158406196',
    projectId: 'grab-73e6f',
    authDomain: 'grab-73e6f.firebaseapp.com',
    storageBucket: 'grab-73e6f.firebasestorage.app',
    measurementId: 'G-65WGQ19ZNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnWZouA7G5eNwmrtTCLvzJZ-5U7BYx6xw',
    appId: '1:24158406196:android:aa001a7d21e92fa09bec61',
    messagingSenderId: '24158406196',
    projectId: 'grab-73e6f',
    storageBucket: 'grab-73e6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEM0Du7_ALFnx5jAElk7mb35wVlauQ18',
    appId: '1:24158406196:ios:99e59f2ec07dbed39bec61',
    messagingSenderId: '24158406196',
    projectId: 'grab-73e6f',
    storageBucket: 'grab-73e6f.firebasestorage.app',
    iosBundleId: 'com.example.grabApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWEM0Du7_ALFnx5jAElk7mb35wVlauQ18',
    appId: '1:24158406196:ios:99e59f2ec07dbed39bec61',
    messagingSenderId: '24158406196',
    projectId: 'grab-73e6f',
    storageBucket: 'grab-73e6f.firebasestorage.app',
    iosBundleId: 'com.example.grabApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbQiNL-FXxjhlnsknBCoBds3s-hfy8SnY',
    appId: '1:24158406196:web:2147b6089716cc8b9bec61',
    messagingSenderId: '24158406196',
    projectId: 'grab-73e6f',
    authDomain: 'grab-73e6f.firebaseapp.com',
    storageBucket: 'grab-73e6f.firebasestorage.app',
    measurementId: 'G-920HHHQGG8',
  );
}
