class FoodDetails {
  String imageURL;
  String name;
  String address;
  String price;
  String priceMax;
  String qc;
  String distance;
  String rating;
  String voucher;

  FoodDetails({
    required this.imageURL,
    required this.name,
    required this.address,
    required this.price,
    required this.priceMax,
    required this.qc,
    required this.distance,
    required this.rating,
    required this.voucher,
  });
}

var listFoodDetails = [
  FoodDetails(
    imageURL: 'assets/images/oLongNhaiSua.jpg',
    name: 'Ô Long Nhài Sữa',
    address: 'Phê La - Lý Thường Kiệt',
    price: '54.000đ',
    priceMax: ' ',
    qc: '  ',
    distance: ' ',
    rating: ' ',
    voucher: ' ',
  ),
  FoodDetails(
    imageURL: 'assets/images/sapaCafe.jpg',
    name: 'SAPA',
    address: 'THAIYEN CAFE - CAFEYENTHAI',
    price: '45.000đ',
    priceMax: ' ',
    qc: ' ',
    distance: ' ',
    rating: ' ',
    voucher: ' ',
  ),
  FoodDetails(
    imageURL: 'assets/images/cafeMuoiHue.jpg',
    name: 'Cà phê muối xứ Huế',
    address: 'Cà Phê Sói',
    price: '40.000đ',
    priceMax: ' ',
    qc: ' ',
    distance: ' ',
    rating: ' ',
    voucher: ' ',
  ),
  FoodDetails(
    imageURL: 'assets/images/lasimi.jpeg',
    name: 'Ô LONG LÀI SỮA KEM PHÔ MAI',
    address: 'LaSiMi Trà Ngon Đậm Vị Phô Mai',
    price: '55.000đ',
    priceMax: ' ',
    qc: ' ',
    distance: ' ',
    rating: ' ',
    voucher: ' ',
  ),
  FoodDetails(
    imageURL: 'assets/images/traSuaGongCha.png',
    name: 'Mua 1 Trà sữa size L - tặng 1 Trà size M',
    address: 'Gong Cha - Hàng Khay',
    price: '90.000đ ',
    priceMax: '120.000đ',
    qc: ' ',
    distance: ' ',
    rating: ' ',
    voucher: ' ',
  ),
  FoodDetails(
    imageURL: 'assets/images/supCuaTrungCut.jpg',
    name: 'Súp cua trứng cút',
    address: 'Súp Cua - Tôn Đức Thắng',
    price: '30.000đ',
    priceMax: ' ',
    qc: ' ',
    distance: ' ',
    rating: ' ',
    voucher: ' ',
  ),
  FoodDetails(
    imageURL: 'assets/images/pkIndian.jpeg',
    name: 'Ô Long Nhài Sữa',
    address: 'Pk Indian restaurant',
    price: '54.000đ',
    priceMax: ' ',
    qc: 'QC ',
    distance: ' 2.4 km ',
    rating: ' 3.6',
    voucher: 'Ưu đãi đến 14K',
  ),
  FoodDetails(
    imageURL: 'assets/images/McDonald.jpg',
    name: 'Ô Long Nhài Sữa',
    address: 'McDonald\'s - Hồ Gươm',
    price: '54.000đ',
    priceMax: ' ',
    qc: 'QC ',
    distance: '1.9 km ',
    rating: ' 4.3',
    voucher: 'Combo Giảm đến 50%-400.000đ',
  ),
  FoodDetails(
    imageURL: 'assets/images/pheLa.jpeg',
    name: 'Ô Long Nhài Sữa',
    address: 'Phê La - Lý Thường Kiệt',
    price: '54.000đ',
    priceMax: ' ',
    qc: ' ',
    distance: ' 1.6 km ',
    rating: '4.4',
    voucher: '50.000đ off',
  ),
  FoodDetails(
    imageURL: 'assets/images/banhMiTuhu.png',
    name: 'Ô Long Nhài Sữa',
    address: 'Bánh Mì Tuhu Bread - Trần Nhân Tông',
    price: '54.000đ',
    priceMax: ' ',
    qc: 'QC ',
    distance: ' 2.9 km ',
    rating: ' 4.4',
    voucher: 'Giảm 3kđ',
  ),
  FoodDetails(
    imageURL: 'assets/images/pkIndian.jpeg',
    name: 'Ô Long Nhài Sữa',
    address: 'Lotteria - Lò Đúc',
    price: '54.000đ',
    priceMax: ' ',
    qc: 'QC ',
    distance: ' 1.6 km ',
    rating: ' 4.4',
    voucher: 'Ưu đãi đến 50k',
  ),
  FoodDetails(
    imageURL: 'assets/images/traSuaTocoToco.jpg',
    name: 'Ô Long Nhài Sữa',
    address: 'TocoToco - Lò Đúc',
    price: '54.000đ',
    priceMax: ' ',
    qc: ' ',
    distance: '  0.8km ',
    rating: ' 4.7',
    voucher: '40.000đ off',
  ),
];
